config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :create, :edit, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks, except: [:new] do
    resources :notes
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, :body, :presence => true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  belongs_to :track,
    primary_key: :id,
    foreign_key: :track_id,
    class_name: "Track"



end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_login, except: [:index, :show]


  def index
    @notes = Note.where(track_id: params[:track_id])
    render :index
  end

  def new
    @note = Note.new
    render :new
  end

  def create
    @note = Note.new(note_params)
    @note.track_id = params[:track_id]
    @note.user_id = current_user.id

    unless @note.save
      flash[:errors] = @note.errors.full_messages
    end
    redirect_to track_url(@note.track_id)
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to track_url(params[:track_id])
  end

private
  def note_params
    params.require(:note).permit(:body)
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_index.html.erb
<ul>
<% notes.each do |note| %>
  <li> Author: <%= note.user.name %></li>
  <li> Note: <%= note.body %></li>
  <li> Date: <%= note.updated_at %></li>
  <% if note.user_id == current_user.id %>
    <%= button_to "delete", track_note_url(note.track_id, note.id), method: :delete %>
  <% end %>
  <hr>
  <br>
<% end %>
</ul>

app/views/notes/_new.html.erb
<form action="<%= track_notes_url(@track) %>" method="post">

  <%= auth_token %>

  <label for="body">Add <%= current_user.name unless current_user.nil?%>'s note here</label>
  <textarea name="note[body]" rows="10" cols="40" id="body">
  </textarea>

  <input type="submit" name= value="">

</form>