config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :create, :edit, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks, except: [:new] do
    resources :notes
  end

end

app/models/track.rb
class Track < ActiveRecord::Base
  TRACK_TYPES = %w(regular bonus)
  validates :title, :album_id, :presence => true
  validates :track_type, :inclusion => { in: TRACK_TYPES }

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: "Album"

  has_one :band,
    through: :album,
    source: :band


  has_many :notes,
    primary_key: :id,
    foreign_key: :track_id,
    class_name: "Note",
    dependent: :destroy


  def self.track_types
    TRACK_TYPES
  end

  def num_of_notes
    notes.count
  end

  def num_of_authors
    notes.distinct.count
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
  end

  def new
    @track = Track.new
    @track.album_id = params[:album_id]
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
    track = Track.find(params[:id])
    track.destroy unless track.nil?
    redirect_to albums_url
  end


  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to albums_url
    else
      flash[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

private
  def track_params
    params.require(:track).permit(:title, :album_id, :track_type, :track_number, :lyrics)
  end

end

app/helpers/tracks_helper.rb
module TracksHelper

  def track_types
    Track.track_types
  end

end

app/views/tracks/_form.html.erb
<% if track.persisted? %>
  <% action, verb, button = track_url(track), "patch", "Edit!" %>
<% else %>
  <% action, verb, button = tracks_url, "post", "Create New Track!" %>
<% end %>

<%= flash[:errors] %>

<form action="<%=  action %>" method="post">
  <input type="hidden" name="_method" value="<%= verb %>">
  <%= auth_token %>

  <label for="title">title</label>
  <input type="text" name="track[title]" id="title" value="<%= track.title %>">

  <br>

  <select name="track[album_id]">
    <option disabled selected>---Pick Album---</option>
    <% all_albums.each do |album| %>
      <option value="<%= album.id %>"
        <% if track.album_id == album.id %>
        <%= "selected" %>
        <% end %>>
      <%= album.title %>
      </option>
    <% end %>
  </selected>
  <br>

  <% track_types.each do |ttype| %>
    <input type="radio" name="track[track_type]"
    value="<%= ttype %>" id="track_type"
    <%= "checked" if track.track_type == ttype %>>
    <label for="track_type"><%= ttype %></label>
  <% end %>

  <br>

  <label for="track_number">track_number</label>
  <input type="integer" name="track[track_number]" id="track_number"
  value="<%= track.track_number %>">

  <br>

  <label for="lyrics">lyrics</label>
  <textarea name="track[lyrics]" rows="10" cols="40" id="lyrics">
  <%= track.lyrics %>
  </textarea>

  <input type="submit" value="<%= button %>">

</form>

app/views/tracks/_tracks.html.erb
  <table border="1">
    <tr>
      <td>title</td>
      <td>track_type</td>
      <td>track_number</td>
    </tr>

    <% tracks.each do |track| %>
    <tr>
      <td><%= track.title %></td>
      <td><%= track.track_type %></td>
      <td><%= track.track_number %></td>
      <td><%= link_to "link", track_url(track.id) %></td>
      <td><%= link_to "edit", edit_track_url(track.id) %></td>
      <td><%= button_to "delete", track_url(track.id), method: :delete %>
    </tr>
    <% end %>
  </table>
<hr>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h1>Create New Track</h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1>Track Info</h1>

<table>
  <tr>
    <td>title</td>
    <td><%= @track.title %></td>
  </tr>

  <tr>
    <td>album</td>
    <td><%= @track.album.title %></td>
  </tr>

  <tr>
    <td>track_number</td>
    <td><%= @track.track_number %></td>
  </tr>

  <tr>
    <td>track_type</td>
    <td><%= @track.track_type %></td>
  </tr>

  <tr>
    <td>lyrics</td>
    <td><%= @track.lyrics %></td>
  </tr>

</table>

<hr>
<%= render "notes/index", notes: @track.notes%>
<%= render "notes/new", track: @track %>