config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :create, :edit, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks, except: [:new] do
    resources :notes
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  ALBUM_TYPES = %w(Studio Live)
  validates :band_id, :title, :presence => true
  validates :album_type, :inclusion => {in: ALBUM_TYPES }


  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: "Band"

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: "Track",
    dependent: :destroy

  def self.album_types
    ALBUM_TYPES
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def new
    @album = Album.new
    @album.band_id = params[:band_id]
    render :new
  end

  def index
    #show all the bands in db.
    render :index
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_url
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to albums_url
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy unless album.nil?
    redirect_to albums_url
  end

  def show
    @album = Album.find(params[:id])
    #show all the albums in the db.
  end


private
  def album_params
    params.require(:album).permit(:title, :band_id, :album_type, :release_date)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper

  def album_types
    Album.album_types
  end

  def all_albums
    Album.all
  end

end

app/views/albums/_albums.html.erb
<ul>
    <table border="1">
      <tr>
        <td>title</td>
        <td>band</td>
        <td>release_date</td>
        <td>type</td>
      <tr>

      <% albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.band.name %></td>
        <td><%= album.release_date %></td>
        <td><%= album.album_type %></td>
        <td><%= link_to "link", album_url(album.id) %></td>
        <td><%= link_to "edit", edit_album_url(album.id) %></td>
        <td><%= button_to "delete", album_url(album.id), method: :delete %></td>
      </tr>
      <% end %>
    </table>
</ul>

app/views/albums/_form.html.erb
<% if album.persisted? %>
  <% verb, button, action = "patch", "Edit!", album_url(album) %>
<% else %>
  <% verb, button, action = "post", "Create New Album", albums_url %>
<% end %>


<%= flash[:errors] %>

<form action="<%= action %>" method="post">
<input type="hidden" name="_method" value="<%= verb %>">
  <%= auth_token %>

  <label for="title">title</label>
  <input type="text" name="album[title]" id="title" value="<%= album.title %>">

  <select name="album[band_id]">
    <option disabled selected> --Pick Band-- </option>
    <% all_bands.each do |band| %>
      <option value="<%= band.id %>"
        <% if album.band_id == band.id %>
        <%= "selected" %>
        <% end %>>
      <%= band.name %></option>
    <% end %>
  </select>

  <% album_types.each do |atype| %>
    <input type="radio"
      name="album[album_type]"
      value="<%= atype %>"
      id="<%= atype %>"
      <% if album.album_type == atype %>
      <%= "checked" %>
      <% end %>>
    <label for="<%= atype %>"><%= atype %></label>
  <% end %>

  <label for="release_date">release_date</label>
  <input type="date" name="album[release_date]" id="release_date" value="<%= album.release_date %>">

  <input type="submit" value="<%= button %>">

</form>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>albums</h1>

<%= render "albums", albums: all_albums %>

app/views/albums/new.html.erb
<h1>Create New Album</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1>Tracks for this Album</h1>


<%= render "tracks/tracks", tracks: @album.tracks %>

<%= link_to "Create New Track for this Album",
    new_album_track_url(@album.id) %>