config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :create, :edit, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks, except: [:new] do
    resources :notes
  end

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, :presence => true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: "Album",
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    render :index
  end

  def new
    render :new
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to bands_url
    else
      flash[:errors] = band.errors.full_messages
      render :new
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy unless band.nil?
    redirect_to bands_url
  end

  def edit
  end

  def update
  end

  def show
    #show the artist, all tracks in db.
    @band = Band.find(params[:id])
    render :show
  end

private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/index.html.erb
<h1>All the bands in database</h1>

<%= flash[:errors] unless flash[:errors].nil? %>

<ul>
    <table>
      <% all_bands.each do |band| %>
      <tr>
        <td><%= link_to band.name, band_url(band.id) %></td>
        <td>
          <%= button_to "delete", band_url(band.id), method: :delete %>
          </td>
      </tr>
      <% end %>
    </table>

</ul>

<br><br>
<%= link_to "Add new band", new_band_url %>

app/views/bands/new.html.erb
<h1>Create New Band</h1>

<%= flash[:errors] %>

<form action="<%= bands_url %>" method="post">
  <%= auth_token %>

  <label for="name">name</label>
  <input type="text" name="band[name]" id="name">

  <input type="submit" value="Create Band">

</form>

app/views/bands/show.html.erb
<h1>This band's album</h1>

<%= render "albums/albums", albums: @band.albums %>


<br><br>
<%= link_to "Add Album for this band", new_band_album_url(@band.id) %>